sudo: required
services:
  - docker

before_install:
  - docker build -t muthuqumar/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true muthuqumar/docker-react npm run test

language: generic

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-ap-northeast-1-303884283160"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: ""$AWS_SECRET_KEY"