name: Deploy MultiDocker
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t muthuqumar/docker-react -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true muthuqumar/docker-react npm test

      - run: docker build -t muthuqumar/multi-client-10-14 ./client
      - run: docker build -t muthuqumar/multi-nginx-10-14 ./nginx
      - run: docker build -t muthuqumar/multi-server-10-14 ./server
      - run: docker build -t muthuqumar/multi-worker-10-14 ./worker

      - run: docker push muthuqumar/multi-client-10-14
      - run: docker push muthuqumar/multi-nginx-10-14
      - run: docker push muthuqumar/multi-server-10-14
      - run: docker push muthuqumar/multi-worker-10-14

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: docker
          environment_name: Docker-env
          existing_bucket_name: elasticbeanstalk-ap-northeast-1-303884283160
          region: ap-northeast-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip